### ISSUE TITLE
docker-composeを利用しアクセスした際にクラッシュする問題

### ISSUE THREAD

**Issue by yuzuki-chi** [tago-lab/site#41]
お世話になってます。t-lab B20のy_takayaです。
この度、t-labサービスをひとつの高スペックマシンに統合する計画が始まり、こちらのサイトを確認しました。

`npm run dev`は問題なく動作し、`localhost:8080`へのアクセスは出来ました。動作も問題ないです。
しかし、docker-compose を使用して動かした場合、`localhost:19000`にアクセスするとコンテナ再起動が繰り返されるようになります。

おそらく関係しているのは `http-server` だと思います。
https://github.com/tago-lab/site/blob/2c32d5f506df2ab46f0b1514b58fc150507784d0/Dockerfile#L17

詳しい挙動は以下の通りです。

#### 起動直後のログ
```bash
Starting up http-server, serving /app/src/.vuepress/dist


http-server version: 14.1.0


http-server settings: 

CORS: disabled

Cache: 3600 seconds

Connection Timeout: 120 seconds

Directory Listings: visible

AutoIndex: visible

Serve GZIP Files: false

Serve Brotli Files: false

Default File Extension: none


Available on:

  http://127.0.0.1:3000

  http://172.21.0.2:3000

Hit CTRL-C to stop the server
```

ここで `localhost:19000` へのアクセスを試みると chromeの`ERR_EMPTY_RESPONSE`エラーが返されます。

#### アクセスした際の挙動

```
[Sun Mar 13 2022 02:49:53 GMT+0000 (UTC)]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"

Starting up http-server, serving /app/src/.vuepress/dist


http-server version: 14.1.0


http-server settings: 

CORS: disabled

Cache: 3600 seconds

Connection Timeout: 120 seconds

Directory Listings: visible

AutoIndex: visible

Serve GZIP Files: false

Serve Brotli Files: false

Default File Extension: none


Available on:

  http://127.0.0.1:3000

  http://172.21.0.2:3000

Hit CTRL-C to stop the server

```

#### エラー発生時の詳しい出力

```bash
tlab_site  | [Sun Mar 13 2022 03:52:06 GMT+0000 (UTC)]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
tlab_site  | /usr/local/lib/node_modules/http-server/lib/core/index.js:246
tlab_site  |           stream = Readable.from(bytes)
tlab_site  |                             ^
tlab_site  | 
tlab_site  | TypeError: Readable.from is not a function
tlab_site  |     at serve (/usr/local/lib/node_modules/http-server/lib/core/index.js:246:29)
tlab_site  |     at fs.stat (/usr/local/lib/node_modules/http-server/lib/core/index.js:419:13)
tlab_site  |     at FSReqWrap.oncomplete (fs.js:150:5)
tlab_site exited with code 1
```

取り急ぎ共有しました。
解決したらプルリクをします。
よろしくお願いします。

**Comment by yuzuki-chi** [comment]
`Readable.from is not a function`
ReadbleはNode.js 12.3.0以降のようでした。
（Dockerfileで指定しているのは10）

https://github.com/nodejs/node/issues/28693
